// SPDX-License-Identifier: Apache-2.0
// Copyright 2026 alibaba/open-code-review Contributors

package model

// RelatedLocation is a secondary file/line anchor for multi-file findings.
type RelatedLocation struct {
	Path      string `json:"path"`
	StartLine int    `json:"start_line,omitempty"`
	EndLine   int    `json:"end_line,omitempty"`
	Note      string `json:"note,omitempty"`
}

// LlmComment represents a code review comment generated by the LLM.
type LlmComment struct {
	Path           string `json:"path"`
	Content        string `json:"content"`
	SuggestionCode string `json:"suggestion_code,omitempty"`
	ExistingCode   string `json:"existing_code,omitempty"`
	StartLine      int    `json:"start_line"`
	EndLine        int    `json:"end_line"`
	Thinking       string `json:"thinking,omitempty"`
	// Category classifies the finding. One of:
	// bug, security, performance, maintainability, test, style, documentation, other.
	Category string `json:"category,omitempty"`
	// Severity indicates the importance of the finding. One of:
	// critical, high, medium, low.
	Severity string `json:"severity,omitempty"`

	// Multi-file / cross-file refactor extensions (optional; viewers ignore if empty).
	RelatedLocations []RelatedLocation `json:"related_locations,omitempty"`
	PlanID           string            `json:"plan_id,omitempty"`
	SmellType        string            `json:"smell_type,omitempty"`
	RefactorKind     string            `json:"refactor_kind,omitempty"`
	ProposedSymbol   string            `json:"proposed_symbol,omitempty"`
}

// CodeReviewResult holds raw LLM-generated review suggestion for a code segment.
type CodeReviewResult struct {
	RelevantFile      string `json:"relevant_file"`
	SuggestionContent string `json:"suggestion_content"`
	ExistingCode      string `json:"existing_code"`
	SuggestionCode    string `json:"suggestion_code"`
}
